const Menu = [
  {
    id: 1,
    image: "images/maggi.jpg",
    name: "maggi",
    category: "Breakfast",
    price: "25₹",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
  {
    id: 4,
    image: "../images/cholebhature.jpg",
    name: "cholabhature",
    category: "Lunch",
    price: "90₹",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
  {
    id: 2,
    image: "images/pakora.jpg",
    name: " pakoora",
    category: "Evening",
    price: "30₹",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
  {
    id: 3,
    image: "images/corn.jpg",
    name: "corn",
    category: "Breakfast",
    price: "20₹",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
  {
    id: 5,
    image: "../images/pizza.jpg",
    name: "pizza",
    category: "Evening",
    price: "150₹",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
  {
    id: 6,
    image: "../images/nonvegthali.jpg",
    name: "Non-Veg Thali",
    category: "Dinner",
    price: "250₹",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
  {
    id: 7,
    image: "../images/sweets.jpg",
    name: "Sweets",
    category: "Dinner",
    price: "80₹",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
  {
    id: 8,
    image: "../images/rajmarice.jpg",
    name: "Rajma Rice",
    category: "Lunch",
    price: "70₹",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
  {
    id: 10,
    image: "../images/samosa.jpg",
    name: "samosa",
    category: "Evening",
    price: "20₹",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
  {
    id: 11,
    image: "../images/vegthali.jpg",
    name: "vegthali",
    category: "Dinner",
    price: "150₹",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
  {
    id: 12,
    image: "../images/palakpaneer.jpg",
    name: "palakpaneer",
    category: "Dinner",
    price: "120₹",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
  {
    id: 13,
    image: "../images/shahipaneer.jpg",
    name: "shahipaneer",
    category: "Dinner",
    price: "120₹",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
  {
    id: 14,
    image: "../images/fries.jpg",
    name: "fries",
    category: "Evening",
    price: "60₹",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
  {
    id: 15,
    image: "../images/friedmomos.jpg",
    name: "friedmomos",
    category: "Evening",
    price: "100₹",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
  {
    id: 16,
    image: "../images/momos.jpg",
    name: "momos",
    category: "Evening",
    price: "50₹",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
  {
    id: 17,
    image: "../images/noodles.jpg",
    name: "noodles",
    category: "Evening",
    price: "70₹",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
  {
    id: 18,
    image: "../images/pavbhaji.jpg",
    name: "pavbhaji",
    category: "Evening",
    price: "120₹",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
  {
    id: 19,
    image: "../images/nonvegburger.jpg",
    name: "nonvegburger",
    category: "Evening",
    price: "90₹",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
  {
    id: 20,
    image: "../images/vegburger.jpg",
    name: "vegburger",
    category: "Evening",
    price: "50₹",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
  {
    id: 21,
    image: "../images/dosa.jpg",
    name: "dosa",
    category: "Breakfast",
    price: "70₹",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
  {
    id: 22,
    image: "../images/idli.jpg",
    name: "idli",
    category: "Breakfast",
    price: "50₹",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
  {
    id: 23,
    image: "../images/paratha.jpg",
    name: "aloo paratha",
    category: "Breakfast",
    price: "30₹",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
  {
    id: 24,
    image: "../images/vada.jpg",
    name: "vada",
    category: "Breakfast",
    price: "40₹",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
  {
    id: 25,
    image: "../images/chicken.jpg",
    name: "butter chicken",
    category: "Dinner",
    price: "150₹",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
  {
    id: 26,
    image: "../images/curry.jpg",
    name: "besan curry",
    category: "Dinner",
    price: "90₹",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
  {
    id: 27,
    image: "../images/daal.jpg",
    name: "Daal Makhani",
    category: "Dinner",
    price: "110₹",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
];

export default Menu;
